# Generated by Django 3.1.7 on 2021-08-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('project_date', models.DateField()),
                ('project_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('project_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('project_image', models.ImageField(upload_to='project_image/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.project')),
            ],
        ),
    ]
