# Generated by Django 3.1.7 on 2021-08-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210819_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
