# Generated by Django 4.2.7 on 2023-11-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_experience_interest_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
