# Generated by Django 4.2.7 on 2023-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='Level',
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('high School', 'High School'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'PhD')], default='high School', max_length=100),
        ),
    ]
